CREATE TABLE yt_videos(
    video_id varchar(11) PRIMARY KEY,
    channel_id text,
    view_count integer,
    comment_count integer,
    like_count integer,
    published_at timestamp,
    title text,
    description text,
    thumbnails json,
    channel_title text,
    category_id integer,
    duration text,
    definition text,
    caption text,
    licensed_content boolean,
    dimension varchar(2),
    embeddable boolean,
    made_for_kids boolean,
    tags text[],
    blocked_regions varchar(2)[],
    thumbnail_hash varchar(64),
    idx integer,
    default_audio_language varchar(7),
    timestamp timestamp,
    trending_regions varchar(2)[],
    thumbnail_iteration integer,
    CONSTRAINT uc_yt_videos_video_id_timestamp UNIQUE(video_id, timestamp)
);