COUNTRIES = {
   "SECONDARY": [
        { "code": "AL", "name": "Albania" },
        { "code": "DZ", "name": "Algeria" },
        { "code": "AR", "name": "Argentina" },
        { "code": "AM", "name": "Armenia" },
        { "code": "AT", "name": "Austria" },
        { "code": "AZ", "name": "Azerbaijan" },
        { "code": "BH", "name": "Bahrain" },
        { "code": "BD", "name": "Bangladesh" },
        { "code": "BY", "name": "Belarus" },
        { "code": "BE", "name": "Belgium" },
        { "code": "BO", "name": "Bolivia" },
        { "code": "BA", "name": "Bosnia And Herzegovina" },
        { "code": "BG", "name": "Bulgaria" },
        { "code": "KH", "name": "Cambodia" },
        { "code": "CL", "name": "Chile" },
        { "code": "CO", "name": "Colombia" },
        { "code": "CR", "name": "Costa Rica" },
        { "code": "HR", "name": "Croatia" },
        { "code": "CY", "name": "Cyprus" },
        { "code": "CZ", "name": "Czech Republic" },
        { "code": "DK", "name": "Denmark" },
        { "code": "DO", "name": "Dominican Republic" },
        { "code": "EC", "name": "Ecuador" },
        { "code": "EG", "name": "Egypt" },
        { "code": "SV", "name": "El Salvador" },
        { "code": "EE", "name": "Estonia" },
        { "code": "FI", "name": "Finland" },
        { "code": "GE", "name": "Georgia" },
        { "code": "GH", "name": "Ghana" },
        { "code": "GR", "name": "Greece" },
        { "code": "GT", "name": "Guatemala" },
        { "code": "HN", "name": "Honduras" },
        { "code": "HK", "name": "Hong Kong" },
        { "code": "HU", "name": "Hungary" },
        { "code": "IS", "name": "Iceland" },
        { "code": "IQ", "name": "Iraq" },
        { "code": "IE", "name": "Ireland" },
        { "code": "JM", "name": "Jamaica" },
        { "code": "JO", "name": "Jordan" },
        { "code": "KZ", "name": "Kazakhstan" },
        { "code": "KE", "name": "Kenya" },
        { "code": "KW", "name": "Kuwait" },
        { "code": "LV", "name": "Latvia" },
        { "code": "LB", "name": "Lebanon" },
        { "code": "LT", "name": "Lithuania" },
        { "code": "LU", "name": "Luxembourg" },
        { "code": "MK", "name": "Macedonia" },
        { "code": "MY", "name": "Malaysia" },
        { "code": "MT", "name": "Malta" },
        { "code": "MD", "name": "Moldova" },
        { "code": "ME", "name": "Montenegro" },
        { "code": "MA", "name": "Morocco" },
        { "code": "NZ", "name": "New Zealand" },
        { "code": "NI", "name": "Nicaragua" },
        { "code": "NG", "name": "Nigeria" },
        { "code": "NO", "name": "Norway" },
        { "code": "OM", "name": "Oman" },
        { "code": "PG", "name": "Papua New Guinea" },
        { "code": "PY", "name": "Paraguay" },
        { "code": "PE", "name": "Peru" },
        { "code": "PL", "name": "Poland" },
        { "code": "PR", "name": "Puerto Rico" },
        { "code": "QA", "name": "Qatar" },
        { "code": "RO", "name": "Romania" },
        { "code": "SN", "name": "Senegal" },
        { "code": "RS", "name": "Serbia" },
        { "code": "SG", "name": "Singapore" },
        { "code": "SK", "name": "Slovakia" },
        { "code": "SI", "name": "Slovenia" },
        { "code": "SE", "name": "Sweden" },
        { "code": "CH", "name": "Switzerland" },
        { "code": "TW", "name": "Taiwan" },
        { "code": "TZ", "name": "Tanzania" },
        { "code": "TN", "name": "Tunisia" },
        { "code": "UG", "name": "Uganda" },
        { "code": "UA", "name": "Ukraine" },
        { "code": "AE", "name": "United Arab Emirates" },
        { "code": "UY", "name": "Uruguay" },
        { "code": "VE", "name": "Venezuela" },
        { "code": "YE", "name": "Yemen" },
        { "code": "LA", "name": "Lao People's Democratic Republic" },
        { "code": "NL", "name": "Netherlands" },
        { "code": "SV", "name": "El Salvador" },
        { "code": "NP", "name": "Nepal" },
        { "code": "LK", "name": "Sri Lanka" },
        { "code": "KH", "name": "Cambodia" },
        { "code": "MN", "name": "Mongolia" },
        { "code": "JM", "name": "Jamaica" },
        { "code": "IL", "name": "Israel" },
        { "code": "BD", "name": "Bangladesh" },
        { "code": "IT", "name": "Italy" },
    ],

    "PRIMARY": [
        { "code": "PT", "name": "Portugal" },
        { "code": "US", "name": "United States" },
        { "code": "BR", "name": "Brazil" },
        { "code": "GB", "name": "United Kingdom" },
        { "code": "ZA", "name": "South Africa" },
        { "code": "RU", "name": "Russian Federation" },
        { "code": "MX", "name": "Mexico" },
        { "code": "ES", "name": "Spain" },
        { "code": "KR", "name": "Korea" },
        { "code": "DE", "name": "Germany" },
        { "code": "FR", "name": "France" },
        { "code": "IN", "name": "India" },
        { "code": "SA", "name": "Saudi Arabia" },
        { "code": "AU", "name": "Australia" },
        { "code": "ID", "name": "Indonesia" },
        { "code": "PK", "name": "Pakistan" },
        { "code": "JP", "name": "Japan" },
        { "code": "TH", "name": "Thailand" },
        { "code": "CA", "name": "Canada" },
        { "code": "VN", "name": "Vietnam" },
        { "code": "PH", "name": "Philippines" },
        { "code": "TR", "name": "Turkey" },
    ],


    "ALL": {
        "AL": {"name": "Albania"},
        "DZ": {"name": "Algeria"},
        "AR": {"name": "Argentina"},
        "AM": {"name": "Armenia"},
        "AT": {"name": "Austria"},
        "AZ": {"name": "Azerbaijan"},
        "BH": {"name": "Bahrain"},
        "BD": {"name": "Bangladesh"},
        "BY": {"name": "Belarus"},
        "BE": {"name": "Belgium"},
        "BO": {"name": "Bolivia"},
        "BA": {"name": "Bosnia And Herzegovina"},
        "BG": {"name": "Bulgaria"},
        "KH": {"name": "Cambodia"},
        "CL": {"name": "Chile"},
        "CO": {"name": "Colombia"},
        "CR": {"name": "Costa Rica"},
        "HR": {"name": "Croatia"},
        "CY": {"name": "Cyprus"},
        "CZ": {"name": "Czech Republic"},
        "DK": {"name": "Denmark"},
        "DO": {"name": "Dominican Republic"},
        "EC": {"name": "Ecuador"},
        "EG": {"name": "Egypt"},
        "SV": {"name": "El Salvador"},
        "EE": {"name": "Estonia"},
        "FI": {"name": "Finland"},
        "GE": {"name": "Georgia"},
        "GH": {"name": "Ghana"},
        "GR": {"name": "Greece"},
        "GT": {"name": "Guatemala"},
        "HN": {"name": "Honduras"},
        "HK": {"name": "Hong Kong"},
        "HU": {"name": "Hungary"},
        "IS": {"name": "Iceland"},
        "IQ": {"name": "Iraq"},
        "IE": {"name": "Ireland"},
        "JM": {"name": "Jamaica"},
        "JO": {"name": "Jordan"},
        "KZ": {"name": "Kazakhstan"},
        "KE": {"name": "Kenya"},
        "KW": {"name": "Kuwait"},
        "LV": {"name": "Latvia"},
        "LB": {"name": "Lebanon"},
        "LT": {"name": "Lithuania"},
        "LU": {"name": "Luxembourg"},
        "MK": {"name": "Macedonia"},
        "MY": {"name": "Malaysia"},
        "MT": {"name": "Malta"},
        "MD": {"name": "Moldova"},
        "ME": {"name": "Montenegro"},
        "MA": {"name": "Morocco"},
        "NZ": {"name": "New Zealand"},
        "NI": {"name": "Nicaragua"},
        "NG": {"name": "Nigeria"},
        "NO": {"name": "Norway"},
        "OM": {"name": "Oman"},
        "PG": {"name": "Papua New Guinea"},
        "PY": {"name": "Paraguay"},
        "PE": {"name": "Peru"},
        "PL": {"name": "Poland"},
        "PR": {"name": "Puerto Rico"},
        "QA": {"name": "Qatar"},
        "RO": {"name": "Romania"},
        "SN": {"name": "Senegal"},
        "RS": {"name": "Serbia"},
        "SG": {"name": "Singapore"},
        "SK": {"name": "Slovakia"},
        "SI": {"name": "Slovenia"},
        "SE": {"name": "Sweden"},
        "CH": {"name": "Switzerland"},
        "TW": {"name": "Taiwan"},
        "TZ": {"name": "Tanzania"},
        "TN": {"name": "Tunisia"},
        "UG": {"name": "Uganda"},
        "UA": {"name": "Ukraine"},
        "AE": {"name": "United Arab Emirates"},
        "UY": {"name": "Uruguay"},
        "VE": {"name": "Venezuela"},
        "YE": {"name": "Yemen"},
        "LA": {"name": "Lao People's Democratic Republic"},
        "NL": {"name": "Netherlands"},
        "NP": {"name": "Nepal"},
        "LK": {"name": "Sri Lanka"},
        "MN": {"name": "Mongolia"},
        "IL": {"name": "Israel"},
        "IT": {"name": "Italy"},
        "PT": {"name": "Portugal"},
        "US": {"name": "United States"},
        "BR": {"name": "Brazil"},
        "GB": {"name": "United Kingdom"},
        "ZA": {"name": "South Africa"},
        "RU": {"name": "Russian Federation"},
        "MX": {"name": "Mexico"},
        "ES": {"name": "Spain"},
        "KR": {"name": "Korea"},
        "DE": {"name": "Germany"},
        "FR": {"name": "France"},
        "IN": {"name": "India"},
        "SA": {"name": "Saudi Arabia"},
        "AU": {"name": "Australia"},
        "ID": {"name": "Indonesia"},
        "PK": {"name": "Pakistan"},
        "JP": {"name": "Japan"},
        "TH": {"name": "Thailand"},
        "CA": {"name": "Canada"},
        "VN": {"name": "Vietnam"},
        "PH": {"name": "Philippines"},
        "TR": {"name": "Turkey"},
    },

}