COUNTRIES = {
    "secondary": [
        { "code": "AL", "name": "Albania" },
        { "code": "DZ", "name": "Algeria" },
        { "code": "AR", "name": "Argentina" },
        { "code": "AM", "name": "Armenia" },
        { "code": "AT", "name": "Austria" },
        { "code": "AZ", "name": "Azerbaijan" },
        { "code": "BH", "name": "Bahrain" },
        { "code": "BD", "name": "Bangladesh" },
        { "code": "BY", "name": "Belarus" },
        { "code": "BE", "name": "Belgium" },
        { "code": "BO", "name": "Bolivia" },
        { "code": "BA", "name": "Bosnia And Herzegovina" },
        { "code": "BG", "name": "Bulgaria" },
        { "code": "KH", "name": "Cambodia" },
        { "code": "CL", "name": "Chile" },
        { "code": "CO", "name": "Colombia" },
        { "code": "CR", "name": "Costa Rica" },
        { "code": "HR", "name": "Croatia" },
        { "code": "CY", "name": "Cyprus" },
        { "code": "CZ", "name": "Czech Republic" },
        { "code": "DK", "name": "Denmark" },
        { "code": "DO", "name": "Dominican Republic" },
        { "code": "EC", "name": "Ecuador" },
        { "code": "EG", "name": "Egypt" },
        { "code": "SV", "name": "El Salvador" },
        { "code": "EE", "name": "Estonia" },
        { "code": "FI", "name": "Finland" },
        { "code": "GE", "name": "Georgia" },
        { "code": "GH", "name": "Ghana" },
        { "code": "GR", "name": "Greece" },
        { "code": "GT", "name": "Guatemala" },
        { "code": "HN", "name": "Honduras" },
        { "code": "HK", "name": "Hong Kong" },
        { "code": "HU", "name": "Hungary" },
        { "code": "IS", "name": "Iceland" },
        { "code": "IQ", "name": "Iraq" },
        { "code": "IE", "name": "Ireland" },
        { "code": "JM", "name": "Jamaica" },
        { "code": "JO", "name": "Jordan" },
        { "code": "KZ", "name": "Kazakhstan" },
        { "code": "KE", "name": "Kenya" },
        { "code": "KW", "name": "Kuwait" },
        { "code": "LV", "name": "Latvia" },
        { "code": "LB", "name": "Lebanon" },
        { "code": "LT", "name": "Lithuania" },
        { "code": "LU", "name": "Luxembourg" },
        { "code": "MK", "name": "Macedonia" },
        { "code": "MY", "name": "Malaysia" },
        { "code": "MT", "name": "Malta" },
        { "code": "MD", "name": "Moldova" },
        { "code": "ME", "name": "Montenegro" },
        { "code": "MA", "name": "Morocco" },
        { "code": "NZ", "name": "New Zealand" },
        { "code": "NI", "name": "Nicaragua" },
        { "code": "NG", "name": "Nigeria" },
        { "code": "NO", "name": "Norway" },
        { "code": "OM", "name": "Oman" },
        { "code": "PG", "name": "Papua New Guinea" },
        { "code": "PY", "name": "Paraguay" },
        { "code": "PE", "name": "Peru" },
        { "code": "PL", "name": "Poland" },
        { "code": "PR", "name": "Puerto Rico" },
        { "code": "QA", "name": "Qatar" },
        { "code": "RO", "name": "Romania" },
        { "code": "SN", "name": "Senegal" },
        { "code": "RS", "name": "Serbia" },
        { "code": "SG", "name": "Singapore" },
        { "code": "SK", "name": "Slovakia" },
        { "code": "SI", "name": "Slovenia" },
        { "code": "SE", "name": "Sweden" },
        { "code": "CH", "name": "Switzerland" },
        { "code": "TW", "name": "Taiwan" },
        { "code": "TZ", "name": "Tanzania" },
        { "code": "TN", "name": "Tunisia" },
        { "code": "UG", "name": "Uganda" },
        { "code": "UA", "name": "Ukraine" },
        { "code": "AE", "name": "United Arab Emirates" },
        { "code": "UY", "name": "Uruguay" },
        { "code": "VE", "name": "Venezuela" },
        { "code": "YE", "name": "Yemen" },
        { "code": "LA", "name": "Lao People's Democratic Republic" },
        { "code": "NL", "name": "Netherlands" },
        { "code": "SV", "name": "El Salvador" },
        { "code": "NP", "name": "Nepal" },
        { "code": "LK", "name": "Sri Lanka" },
        { "code": "KH", "name": "Cambodia" },
        { "code": "MN", "name": "Mongolia" },
        { "code": "JM", "name": "Jamaica" },
        { "code": "IL", "name": "Israel" },
        { "code": "BD", "name": "Bangladesh" },
        { "code": "IT", "name": "Italy" },
    ],
    
    "primary": [
        { "code": "PT", "name": "Portugal" },
        { "code": "US", "name": "United States" },
        { "code": "BR", "name": "Brazil" },
        { "code": "GB", "name": "United Kingdom" },
        { "code": "ZA", "name": "South Africa" },
        { "code": "RU", "name": "Russian Federation" },
        { "code": "MX", "name": "Mexico" },
        { "code": "ES", "name": "Spain" },
        { "code": "KR", "name": "Korea" },
        { "code": "DE", "name": "Germany" },
        { "code": "FR", "name": "France" },
        { "code": "IN", "name": "India" },
        { "code": "SA", "name": "Saudi Arabia" },
        { "code": "AU", "name": "Australia" },
        { "code": "ID", "name": "Indonesia" },
        { "code": "PK", "name": "Pakistan" },
        { "code": "JP", "name": "Japan" },
        { "code": "TH", "name": "Thailand" },
        { "code": "CA", "name": "Canada" },
        { "code": "VN", "name": "Vietnam" },
        { "code": "PH", "name": "Philippines" },
        { "code": "TR", "name": "Turkey" },
    ],
}


