COUNTRIES = {
    "PRIMARY": {
        "PT": {"name": "Portugal"},
        "US": {"name": "United States"},
        "BR": {"name": "Brazil"},
        "GB": {"name": "United Kingdom"},
        "ZA": {"name": "South Africa"},
        "RU": {"name": "Russian Federation"},
        "MX": {"name": "Mexico"},
        "ES": {"name": "Spain"},
        "KR": {"name": "Korea"},
        "DE": {"name": "Germany"},
        "FR": {"name": "France"},
        "IN": {"name": "India"},
        "SA": {"name": "Saudi Arabia"},
        "AU": {"name": "Australia"},
        "ID": {"name": "Indonesia"},
        "PK": {"name": "Pakistan"},
        "JP": {"name": "Japan"},
        "TH": {"name": "Thailand"},
        "CA": {"name": "Canada"},
        "VN": {"name": "Vietnam"},
        "PH": {"name": "Philippines"},
        "TR": {"name": "Turkey"},
    },

    "SECONDARY": {
        "AL": {"name": "Albania"},
        "DZ": {"name": "Algeria"},
        "AR": {"name": "Argentina"},
        "AM": {"name": "Armenia"},
        "AT": {"name": "Austria"},
        "AZ": {"name": "Azerbaijan"},
        "BH": {"name": "Bahrain"},
        "BD": {"name": "Bangladesh"},
        "BY": {"name": "Belarus"},
        "BE": {"name": "Belgium"},
        "BO": {"name": "Bolivia"},
        "BA": {"name": "Bosnia And Herzegovina"},
        "BG": {"name": "Bulgaria"},
        "KH": {"name": "Cambodia"},
        "CL": {"name": "Chile"},
        "CO": {"name": "Colombia"},
        "CR": {"name": "Costa Rica"},
        "HR": {"name": "Croatia"},
        "CY": {"name": "Cyprus"},
        "CZ": {"name": "Czech Republic"},
        "DK": {"name": "Denmark"},
        "DO": {"name": "Dominican Republic"},
        "EC": {"name": "Ecuador"},
        "EG": {"name": "Egypt"},
        "SV": {"name": "El Salvador"},
        "EE": {"name": "Estonia"},
        "FI": {"name": "Finland"},
        "GE": {"name": "Georgia"},
        "GH": {"name": "Ghana"},
        "GR": {"name": "Greece"},
        "GT": {"name": "Guatemala"},
        "HN": {"name": "Honduras"},
        "HK": {"name": "Hong Kong"},
        "HU": {"name": "Hungary"},
        "IS": {"name": "Iceland"},
        "IQ": {"name": "Iraq"},
        "IE": {"name": "Ireland"},
        "JM": {"name": "Jamaica"},
        "JO": {"name": "Jordan"},
        "KZ": {"name": "Kazakhstan"},
        "KE": {"name": "Kenya"},
        "KW": {"name": "Kuwait"},
        "LV": {"name": "Latvia"},
        "LB": {"name": "Lebanon"},
        "LT": {"name": "Lithuania"},
        "LU": {"name": "Luxembourg"},
        "MK": {"name": "Macedonia"},
        "MY": {"name": "Malaysia"},
        "MT": {"name": "Malta"},
        "MD": {"name": "Moldova"},
        "ME": {"name": "Montenegro"},
        "MA": {"name": "Morocco"},
        "NZ": {"name": "New Zealand"},
        "NI": {"name": "Nicaragua"},
        "NG": {"name": "Nigeria"},
        "NO": {"name": "Norway"},
        "OM": {"name": "Oman"},
        "PG": {"name": "Papua New Guinea"},
        "PY": {"name": "Paraguay"},
        "PE": {"name": "Peru"},
        "PL": {"name": "Poland"},
        "PR": {"name": "Puerto Rico"},
        "QA": {"name": "Qatar"},
        "RO": {"name": "Romania"},
        "SN": {"name": "Senegal"},
        "RS": {"name": "Serbia"},
        "SG": {"name": "Singapore"},
        "SK": {"name": "Slovakia"},
        "SI": {"name": "Slovenia"},
        "SE": {"name": "Sweden"},
        "CH": {"name": "Switzerland"},
        "TW": {"name": "Taiwan"},
        "TZ": {"name": "Tanzania"},
        "TN": {"name": "Tunisia"},
        "UG": {"name": "Uganda"},
        "UA": {"name": "Ukraine"},
        "AE": {"name": "United Arab Emirates"},
        "UY": {"name": "Uruguay"},
        "VE": {"name": "Venezuela"},
        "YE": {"name": "Yemen"},
        "LA": {"name": "Lao People's Democratic Republic"},
        "NL": {"name": "Netherlands"},
        "NP": {"name": "Nepal"},
        "LK": {"name": "Sri Lanka"},
        "MN": {"name": "Mongolia"},
        "IL": {"name": "Israel"},
        "IT": {"name": "Italy"},
    },

    "ALL": {
        "AL": {"name": "Albania"},
        "DZ": {"name": "Algeria"},
        "AR": {"name": "Argentina"},
        "AM": {"name": "Armenia"},
        "AT": {"name": "Austria"},
        "AZ": {"name": "Azerbaijan"},
        "BH": {"name": "Bahrain"},
        "BD": {"name": "Bangladesh"},
        "BY": {"name": "Belarus"},
        "BE": {"name": "Belgium"},
        "BO": {"name": "Bolivia"},
        "BA": {"name": "Bosnia And Herzegovina"},
        "BG": {"name": "Bulgaria"},
        "KH": {"name": "Cambodia"},
        "CL": {"name": "Chile"},
        "CO": {"name": "Colombia"},
        "CR": {"name": "Costa Rica"},
        "HR": {"name": "Croatia"},
        "CY": {"name": "Cyprus"},
        "CZ": {"name": "Czech Republic"},
        "DK": {"name": "Denmark"},
        "DO": {"name": "Dominican Republic"},
        "EC": {"name": "Ecuador"},
        "EG": {"name": "Egypt"},
        "SV": {"name": "El Salvador"},
        "EE": {"name": "Estonia"},
        "FI": {"name": "Finland"},
        "GE": {"name": "Georgia"},
        "GH": {"name": "Ghana"},
        "GR": {"name": "Greece"},
        "GT": {"name": "Guatemala"},
        "HN": {"name": "Honduras"},
        "HK": {"name": "Hong Kong"},
        "HU": {"name": "Hungary"},
        "IS": {"name": "Iceland"},
        "IQ": {"name": "Iraq"},
        "IE": {"name": "Ireland"},
        "JM": {"name": "Jamaica"},
        "JO": {"name": "Jordan"},
        "KZ": {"name": "Kazakhstan"},
        "KE": {"name": "Kenya"},
        "KW": {"name": "Kuwait"},
        "LV": {"name": "Latvia"},
        "LB": {"name": "Lebanon"},
        "LT": {"name": "Lithuania"},
        "LU": {"name": "Luxembourg"},
        "MK": {"name": "Macedonia"},
        "MY": {"name": "Malaysia"},
        "MT": {"name": "Malta"},
        "MD": {"name": "Moldova"},
        "ME": {"name": "Montenegro"},
        "MA": {"name": "Morocco"},
        "NZ": {"name": "New Zealand"},
        "NI": {"name": "Nicaragua"},
        "NG": {"name": "Nigeria"},
        "NO": {"name": "Norway"},
        "OM": {"name": "Oman"},
        "PG": {"name": "Papua New Guinea"},
        "PY": {"name": "Paraguay"},
        "PE": {"name": "Peru"},
        "PL": {"name": "Poland"},
        "PR": {"name": "Puerto Rico"},
        "QA": {"name": "Qatar"},
        "RO": {"name": "Romania"},
        "SN": {"name": "Senegal"},
        "RS": {"name": "Serbia"},
        "SG": {"name": "Singapore"},
        "SK": {"name": "Slovakia"},
        "SI": {"name": "Slovenia"},
        "SE": {"name": "Sweden"},
        "CH": {"name": "Switzerland"},
        "TW": {"name": "Taiwan"},
        "TZ": {"name": "Tanzania"},
        "TN": {"name": "Tunisia"},
        "UG": {"name": "Uganda"},
        "UA": {"name": "Ukraine"},
        "AE": {"name": "United Arab Emirates"},
        "UY": {"name": "Uruguay"},
        "VE": {"name": "Venezuela"},
        "YE": {"name": "Yemen"},
        "LA": {"name": "Lao People's Democratic Republic"},
        "NL": {"name": "Netherlands"},
        "NP": {"name": "Nepal"},
        "LK": {"name": "Sri Lanka"},
        "MN": {"name": "Mongolia"},
        "IL": {"name": "Israel"},
        "IT": {"name": "Italy"},
        "PT": {"name": "Portugal"},
        "US": {"name": "United States"},
        "BR": {"name": "Brazil"},
        "GB": {"name": "United Kingdom"},
        "ZA": {"name": "South Africa"},
        "RU": {"name": "Russian Federation"},
        "MX": {"name": "Mexico"},
        "ES": {"name": "Spain"},
        "KR": {"name": "Korea"},
        "DE": {"name": "Germany"},
        "FR": {"name": "France"},
        "IN": {"name": "India"},
        "SA": {"name": "Saudi Arabia"},
        "AU": {"name": "Australia"},
        "ID": {"name": "Indonesia"},
        "PK": {"name": "Pakistan"},
        "JP": {"name": "Japan"},
        "TH": {"name": "Thailand"},
        "CA": {"name": "Canada"},
        "VN": {"name": "Vietnam"},
        "PH": {"name": "Philippines"},
        "TR": {"name": "Turkey"},
    },

}